Inclui o README do repositório
feministech/maratona2 pull request #2
Opened 2022-05-29 16:27 UTC by patriciavillela

Issue #1

2022-05-31 03:37 UTC, LelePG requested changes
apontei alguns pontos que podem deixar o README ainda mais legal :)

2022-05-31 03:37 UTC, LelePG commented on README.md
> +|  |  |   |   |   |
Tirar duas barrinhas daqui e ta linha de baixo pra tabela ficar só com as três colunas que a gente tem de conteúdo

2022-05-31 03:37 UTC, LelePG commented on README.md
> +Esse é o repositório que contém o código para o site da segunda maratona Live Coder Girls BR.
Também é interessante colocar um "clique aqui" pra acessar o site se o site ainda estiver disponível

2022-05-31 03:37 UTC, LelePG commented on README.md
> +![Screenshot da página inteira do site](https://user-images.githubusercontent.com/2437447/170879025-21f5de26-c9f2-4009-89de-e4b2318fda49.png)
Colocar a imagem pra cima do cronograma

2022-06-02 00:51 UTC, patriciavillela commented on README.md
> +|  |  |   |   |   |
Feito.

2022-06-02 00:51 UTC, patriciavillela commented on README.md
> +Esse é o repositório que contém o código para o site da segunda maratona Live Coder Girls BR.
Feito

2022-06-02 00:51 UTC, patriciavillela commented on README.md
> +![Screenshot da página inteira do site](https://user-images.githubusercontent.com/2437447/170879025-21f5de26-c9f2-4009-89de-e4b2318fda49.png)
Feito.

2022-06-04 00:46 UTC, merged